AnaliseProjeto/querojobs.mdj
=> Correção implementada. Resolve #26.

AnaliseProjeto/querojobs.mdj
=> Modificações propostas realizadas. Resolve #27

AnaliseProjeto/querojobs.mdj
Favor revisar se as alterações feitas estão de acordo com o que foi proposto na issue em questão.
=> As alterações foram feitas. Resolve #28

AnaliseProjeto/querojobs.mdj
Analisar o caso de uso manter currículo.
=> Alteração do caso de uso manter currículo. Resolve #30

AnaliseProjeto/querojobs.mdj
Além disso, foram necessárias algumas modificações em "submeter currículo" e "submeter vaga disponível". Resolve #46 #39
=> O diagrama para "Manter Vaga" foi modificado.

AnaliseProjeto/querojobs.mdj
-Migrei Currículo para Candidato
-Modifiquei a lógica de ligação entre escolaridade e curso para instituição e curso.
-Modifiquei o Controlador que estava para ControladorVaga
-Adicionei o atributo cargaHoraria na entidade Vaga.
-No controladorVaga adicionei o método "salvar" para ter a opção de salvar a vaga e disponibilizá-la depois e o método "aplicar" para permitir que o candidato se candidate para vaga
-Fiz o merge de duas entidades "Vaga"
-Alterei o diagrama de classe "Submeter Curriculo" para "Candidatar para Vaga";
-Modifiquei "ControladorCandidatos" para "ControladorVaga" e consequentemente os elementos mais importantes desse diagrama passou a ser "vaga"
-Adicionei o método "selecionarCandidato" ao "ControladorVaga"
-A entidade Candidato em Manter Candidato se relaciona com Cargo …
=> Migrei Currículo para Candidato

AnaliseProjeto/querojobs.mdj
=> Alterações no manter empresa. #48

AnaliseProjeto/querojobs.mdj
Analisar os diagramas de selecionar candidato.
=> Branch milena38

AnaliseProjeto/querojobs.mdj
Vê se alterações atende aos requisitos da tarefa
=> Diagrama de caso de uso de autenticar usuario foi atualizada

AnaliseProjeto/querojobs.mdj
Analisar diagrama de caso de uso e de sequencia de consultar vaga
=> ADD: Diagrama de caso de uso e de sequencia de consultar vaga

AnaliseProjeto/querojobs.mdj
Analisar se atende o que a questao está pedindo.
=> ADD: Diagrama de caso de uso de sequencia de requisitos. Resolve #53

AnaliseProjeto/querojobs.mdj
adicionei a entidade EmpresaVaga, invocada quando uma empresa submete uma vaga criada.
=> Modificação na classe "Submeter Vaga Disponível"

AnaliseProjeto/querojobs.mdj
Analisar as alterações que foram feitas.
=> [Fix] buscando empresa antes de inserir vaga

AnaliseProjeto/querojobs.mdj
Favor revisar se o relacionamento foi adicionado corretamente.
=> Relacionamento adicionado.

AnaliseProjeto/querojobs.mdj
**-Consultar Candidatos- -aceitar confirmação vaga- e  -selecionar candidato- foram corrigidos.**
**O diagrama inserir vaga já estava cumprindo o requisito proposto.**
Favor verificar se o que foi proposto foi cumprido.
=> Corrigido os collaborations

AnaliseProjeto/querojobs.mdj
Analisar se as persistencias foram adicionadas corretamente
=> Branch milena91

AnaliseProjeto/querojobs.mdj
=> ADD:: Diagrama de estados para Candidato

AnaliseProjeto/querojobs.mdj
Favor, verificar se o DER está correto.  Resolve #76
=> DER atualizado.

Codigo/QueroJobs/Core/Services/IRoleService.cs, Codigo/QueroJobs/Services/RoleService.cs
=> Implementação do caso de uso ManterCargo

Codigo/QueroJobs/Core/Services/ICompetenceService.cs, Codigo/QueroJobs/Services/CompetenceService.cs
=> Implementação do caso de uso ManterCompetência 

Codigo/QueroJobs/QueroJobsWEB/Program.cs
=> ADD:: Injeções de dependência para RoleServices e CompetenceServices.

Codigo/QueroJobs/QueroJobsWEB/Views/Company/Create.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Company/Delete.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Company/Details.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Company/Edit.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Company/Index.cshtml
=> [UPDATE] Update views with validation

Codigo/QueroJobs/Core/DTO/CandidateDTO.cs, Codigo/QueroJobs/Core/SeedingService.cs, Codigo/QueroJobs/QueroJobsWEB/Controllers/CandidateController.cs, Codigo/QueroJobs/QueroJobsWEB/Mappers/CandidateProfile.cs, Codigo/QueroJobs/QueroJobsWEB/Models/CandidateModel.cs, Codigo/QueroJobs/QueroJobsWEB/Program.cs, Codigo/QueroJobs/QueroJobsWEB/QueroJobsWEB.csproj, Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Create.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Delete.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Details.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Edit.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Index.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
=> Implementado o caso de uso manter candidato

Codigo/QueroJobs/Core/SeedingService.cs, Codigo/QueroJobs/QueroJobsWEB/Controllers/CompetenceController.cs, Codigo/QueroJobs/QueroJobsWEB/Controllers/RoleController.cs, Codigo/QueroJobs/QueroJobsWEB/Mappers/CompetenceProfile.cs, Codigo/QueroJobs/QueroJobsWEB/Mappers/RoleProfile.cs, Codigo/QueroJobs/QueroJobsWEB/Models/CompetenceModel.cs, Codigo/QueroJobs/QueroJobsWEB/Models/RoleModel.cs, Codigo/QueroJobs/QueroJobsWEB/Program.cs, Codigo/QueroJobs/QueroJobsWEB/Views/Competence/Create.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Competence/Delete.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Competence/Edit.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Competence/Index.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Role/Create.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Role/Delete.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Role/Edit.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Role/Index.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml
Finalização dos casos de uso Role e Competence.
=> Finalização dos casos de uso Role e Competence

Codigo/README.md
Agora está usandoo o banco correto
=> ADD: correção de readme

Codigo/QueroJobs/QueroJobsWEBTests/Controllers/CompetenceControllerTests.cs, Codigo/QueroJobs/ServicesTests/CompetenceServiceTests.cs
Finalização do caso de teste de unidade para Competence.
=> Caso de teste implementado para CompetenceController e CompetenceService

Codigo/QueroJobs/QueroJobsWEBTests/Controllers/CourseControllerTests.cs, Codigo/QueroJobs/ServicesTests/CourseServiceTests.cs
=> Finalização do caso de teste de unidade para Course.

Codigo/QueroJobs/QueroJobsWEB/Controllers/CandidateController.cs, Codigo/QueroJobs/QueroJobsWEB/Models/CandidateModel.cs, Codigo/QueroJobs/QueroJobsWEB/Models/CompanyModel.cs, Codigo/QueroJobs/QueroJobsWEB/QueroJobsWEB.csproj, Codigo/QueroJobs/QueroJobsWEB/Views/Candidate/Create.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Company/Create.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Company/Create.cshtml.css, Codigo/QueroJobs/QueroJobsWEB/Views/Shared/_Layout.cshtml, Codigo/QueroJobs/Utils/CepAttribute.cs
--Empresa--
Tela do caso de uso de cadastro de empresa implementada.
PS: Falta mudar a cor do header e do footer nessa tela
--Candidato--
Mudei os nomes das deficiências
Mudei o tamanho do h1 de candidate
Alterei o state para o tipo select
Resolve 213.
=> Tela do caso de uso de cadastro de empresa implementada

Codigo/QueroJobs/QueroJobsWEB/Views/Admin/Index.cshtml, Codigo/QueroJobs/QueroJobsWEB/Views/Admin/Index.cshtml.css, Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/QuerojobsComponents.css, Codigo/QueroJobs/QueroJobsWEB/wwwroot/css/styles.css
Correção dos botões e centralização dos componentes.
=> FIX:: Centralização e botões

Codigo/QueroJobs/QueroJobsWEB/Controllers/InterestedCandidatesController.cs
Controladora de Candidatos Interessados Inicializada. #234
=> Controladora de Candidatos Interessados 

Codigo/QueroJobs/Core/Services/ICompanyService.cs, Codigo/QueroJobs/Core/Services/IVacancyService.cs, Codigo/QueroJobs/Services/CompanyService.cs, Codigo/QueroJobs/Services/VacancyService.cs
Foi efetuada a troca de qual serviço é o responsável pela implementação do método obter candidatos interessados. Company -> Vacancy. Close #243
=> Troca do responsável por implementar o método obter candidatos interessados.

Codigo/QueroJobs/QueroJobsWEBTests/Controllers/CandidateControllerTests.cs
Reverts marcosdosea/QueroJobs#260
=> Revert "[Update] Campos agora tem valores proximos com a realidade"

Codigo/QueroJobs/QueroJobsWEBTests/Controllers/CandidateControllerTests.cs
Reverts marcosdosea/QueroJobs#261
=> [Update] Campos agora tem valores proximos com a realidade

Codigo/QueroJobs/QueroJobsWEBTests/Controllers/AdminControllerTests.cs
=> Implementação Iniciada.

Testes/QueroJobs-AutenticarUsuario.side
Analisar os testes automatizados de autenticar usuário.
=> [Add] Selenium test Autenticar Usuario
